"use client";

import Image from "next/image";
import { Navbar } from "@/components/Navbar";
import { ContactForm } from "@/components/ContactForm";
import { BrandMark } from "@/components/BrandMark";
import { Icon } from "@/components/Icons";
import { useLanguage } from "@/components/LanguageProvider";

const icons = ["phone", "bag", "gift", "calendar", "qr", "plug"] as const;
const pairList = (value: string) => value.split("|").map((item) => item.split("~"));

export default function Home() {
  const { t } = useLanguage();
  const hero = t("heroTitle").split("|"), heroActions = t("heroActions").split("|"), proofs = t("heroProof").split("|"), heroCard = t("heroCard").split("|");
  const problem = t("problemHead").split("|"), solution = t("solutionHead").split("|"), eco = t("ecosystem").split("|");
  const featureHead = t("featuresHead").split("|"), features = pairList(t("featureCards"));
  const appHead = t("appHead").split("|"), appBenefits = pairList(t("appBenefits")), appUi = t("appUi").split("|");
  const loyaltyHead = t("loyaltyHead").split("|"), loyaltyItems = pairList(t("loyaltyItems")), loyaltyUi = t("loyaltyUi").split("|");
  const resHead = t("reservationsHead").split("|"), res = t("reservationsUi").split("|");
  const intHead = t("integrationsHead").split("|"), int = t("integrationsUi").split("|");
  const priceHead = t("pricingHead").split("|"), price = t("pricingUi").split("|");
  const contactHead = t("contactHead").split("|"), contactSteps = pairList(t("contactSteps"));
  const footer = t("footerUi").split("|");
  return <main id="top"><Navbar/>
    <section className="hero"><Image src="/images/cangujet-restaurant-hero.png" alt={t("heroAlt")} fill priority className="hero-image" sizes="100vw"/><div className="hero-scrim"/><div className="container hero-content"><div className="eyebrow eyebrow-on-dark"><span/>{t("heroEyebrow")}</div><h1>{hero[0]}<br/><em>{hero[1]}</em><br/>{hero[2]}</h1><p>{t("heroText")}</p><div className="hero-actions"><a className="button" href="#contact">{heroActions[0]} <Icon name="arrow" size={18}/></a><a className="button button-ghost" href="#solution">{heroActions[1]}</a></div><div className="hero-proof">{proofs.map((x) => <span key={x}><Icon name="check" size={16}/>{x}</span>)}</div></div><div className="hero-card"><div className="live-dot"><i/>{heroCard[0]}</div><strong>€42.80</strong><span>{heroCard[1]}</span><div className="commission"><span>{heroCard[2]}</span><b>€0.00</b></div></div></section>

    <section className="problem" id="problem"><div className="container problem-grid"><div><div className="eyebrow eyebrow-orange">{problem[0]}</div><h2>{problem[1]}<br/><em>{problem[2]}</em></h2></div><div className="problem-copy"><p className="lead">{t("problemText")}</p><div className="problem-list">{pairList(t("problemItems")).map(([title,text],i) => <div key={title}><span>0{i+1}</span><p><b>{title}</b> {text}</p></div>)}</div></div></div></section>

    <section className="solution" id="solution"><div className="container"><div className="section-heading centered light-heading"><div className="eyebrow eyebrow-blue">{solution[0]}</div><h2>{solution[1]} <em>{solution[2]}</em></h2><p>{t("solutionText")}</p></div><div className="ecosystem"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="ecosystem-center"><BrandMark light/><small>{eco[0]}</small></div>{icons.map((icon,i) => <div className={`eco-item eco-${i+1}`} key={eco[i+1]}><Icon name={i===5?"users":icon}/><span>{eco[i+1]}</span></div>)}</div></div></section>

    <section className="features section" id="features"><div className="container"><div className="section-heading split-heading"><div><div className="eyebrow">{featureHead[0]}</div><h2>{featureHead[1]}<br/><em>{featureHead[2]}</em></h2></div><p>{t("featuresText")}</p></div><div className="feature-grid">{features.map(([title,text],i) => <article className="feature-card" key={title}><div className="feature-top"><span className="icon-box"><Icon name={icons[i]}/></span><small>0{i+1}</small></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

    <section className="app-showcase section"><div className="container showcase-grid"><div className="phone-stage"><div className="phone-glow"/><div className="phone-mockup"><div className="phone-speaker"/><div className="app-screen"><div className="app-nav"><b>CASA</b><span>⌁</span></div><div className="food-photo"><span>{appUi[1]}</span><b>{appUi[2]}</b></div><div className="app-pills"><span className="active">{appUi[3]}</span><span>{appUi[4]}</span><span>{appUi[5]}</span></div><div className="app-item"><div className="dish dish-one"/><p><b>{appUi[6]}</b><small>{appUi[7]} · €18.50</small></p><button aria-label="Add">+</button></div><div className="app-item"><div className="dish dish-two"/><p><b>{appUi[8]}</b><small>{appUi[9]} · €12.00</small></p><button aria-label="Add">+</button></div><div className="app-bottom"><span>⌂<small>{appUi[10]}</small></span><span>◇<small>{appUi[11]}</small></span><span>♡<small>{appUi[12]}</small></span></div></div></div><div className="floating-badge badge-order"><Icon name="check"/><p><b>{appUi[13]}</b><small>{appUi[14]}</small></p></div><div className="floating-badge badge-brand"><Icon name="phone"/><p><b>{appUi[15]}</b><small>{appUi[16]}</small></p></div></div><div className="showcase-copy"><div className="eyebrow">{appHead[0]}</div><h2>{appHead[1]} <em>{appHead[2]}</em></h2><p className="lead">{t("appText")}</p><ul className="check-list">{appBenefits.map(([title,text]) => <li key={title}><span><Icon name="check"/></span><div><b>{title}</b><p>{text}</p></div></li>)}</ul><a href="#contact" className="inline-link">{appUi[0]} <Icon name="arrow" size={18}/></a></div></div></section>

    <section className="loyalty section"><div className="container loyalty-grid"><div className="loyalty-copy"><div className="eyebrow eyebrow-orange">{loyaltyHead[0]}</div><h2>{loyaltyHead[1]} <em>{loyaltyHead[2]}</em></h2><p className="lead">{t("loyaltyText")}</p><div className="reward-list">{loyaltyItems.map(([title,text],i) => <div key={title}><span>0{i+1}</span><p><b>{title}</b><small>{text}</small></p></div>)}</div></div><div className="loyalty-card-wrap"><div className="loyalty-card"><div className="loyalty-brand"><span>C</span><p><b>CASA</b><small>{loyaltyUi[0]}</small></p></div><p className="points-label">{loyaltyUi[1]}</p><strong>1,240 <small>{loyaltyUi[2]}</small></strong><div className="progress"><i/></div><p className="points-copy">{loyaltyUi[3]}</p><div className="reward"><span>☕</span><p><b>{loyaltyUi[4]}</b><small>{loyaltyUi[5]}</small></p></div></div><div className="return-card"><Icon name="chart"/><div><small>{loyaltyUi[6]}</small><b>+28%</b></div><span>↗</span></div></div></div></section>

    <section className="reservations section"><div className="container reservation-grid"><div className="reservation-ui"><div className="res-header"><div><small>{res[3]}</small><b>{res[4]}</b></div><span>{res[5]}</span></div><div className="res-stats"><span><small>{res[6]}</small><b>86</b></span><span><small>{res[7]}</small><b>24</b></span><span><small>{res[8]}</small><b>82%</b></span></div><div className="timeline">{[["19:00",`${res[9]} 4 · 2 ${res[11]}`],["19:30",`${res[9]} 8 · 4 ${res[11]}`],["20:00",`${res[10]} · 6 ${res[11]}`],["20:30",`${res[9]} 2 · 2 ${res[11]}`]].map(([time,label]) => <div className="time-row" key={time}><span>{time}</span><i/><b>{label}</b></div>)}</div></div><div className="showcase-copy"><div className="eyebrow">{resHead[0]}</div><h2>{resHead[1]}<br/><em>{resHead[2]}</em></h2><p className="lead">{t("reservationsText")}</p><div className="mini-benefits">{res.slice(0,3).map((x,i) => <span key={x}><Icon name={i===0?"clock":i===1?"users":"shield"}/><b>{x}</b></span>)}</div></div></div></section>

    <section className="integrations section" id="integrations"><div className="container"><div className="section-heading centered"><div className="eyebrow">{intHead[0]}</div><h2>{intHead[1]} <em>{intHead[2]}</em></h2><p>{t("integrationsText")}</p></div><div className="integration-row"><div className="integration-card featured-integration"><span className="zonesoft-mark">Z</span><b>Zonesoft</b><small>{int[0]}</small></div>{[["wallet",int[1],int[2]],["bag",int[3],int[4]],["chart",int[5],int[6]]].map(([icon,title,text]) => <div className="integration-card" key={title}><Icon name={icon as "wallet"|"bag"|"chart"} size={28}/><b>{title}</b><small>{text}</small></div>)}</div><p className="integration-note"><span>+</span> {int[7]} <a href="#contact">{int[8]}</a></p></div></section>

    <section className="pricing section" id="pricing"><div className="container pricing-box"><div className="pricing-copy"><div className="eyebrow eyebrow-blue">{priceHead[0]}</div><h2>{priceHead[1]} <em>{priceHead[2]}</em></h2><p>{t("pricingText")}</p><div className="pricing-points">{price.slice(0,3).map((x) => <span key={x}><Icon name="check"/> {x}</span>)}</div></div><div className="demo-card"><span className="demo-icon">↗</span><h3>{price[3]}</h3><p>{price[4]}</p><a href="#contact" className="button button-full">{price[5]} <Icon name="arrow" size={18}/></a><small>{price[6]}</small></div></div></section>

    <section className="contact section" id="contact"><div className="container contact-grid"><div className="contact-copy"><div className="eyebrow">{contactHead[0]}</div><h2>{contactHead[1]} <em>{contactHead[2]}</em></h2><p>{t("contactText")}</p>{contactSteps.map(([title,text],i) => <div className="contact-detail" key={title}><span>0{i+1}</span><p><b>{title}</b><small>{text}</small></p></div>)}</div><ContactForm/></div></section>

    <footer><div className="container footer-top"><div className="footer-brand"><BrandMark light/><p>{t("footerText")}</p></div><div className="footer-links"><div><b>{footer[0]}</b><a href="#features">{footer[1]}</a><a href="#solution">{footer[2]}</a><a href="#integrations">{footer[3]}</a><a href="#pricing">{footer[4]}</a></div><div><b>{footer[5]}</b><a href="#contact">{footer[6]}</a><a href="#contact">{footer[7]}</a><span>{footer[8]}</span></div></div></div><div className="container footer-bottom"><p>© 2026 {footer[9]}</p><div><a href="#">{footer[10]}</a><a href="#">{footer[11]}</a></div></div></footer>
  </main>;
}
